name: Create an S3 Buckets

on:
  push:
    branches:
      - feature/aws
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  create_bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install
        working-directory: frontend

      - name: Build frontend
        run: pnpm run build
        working-directory: frontend

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        env:
          TF_VAR_bucket_name: ${{ secrets.BUCKET_NAME }}
        run: terraform plan -var="bucket_name=${TF_VAR_bucket_name}"
        working-directory: terraform

      - name: Terraform Apply
        env:
          TF_VAR_bucket_name: ${{ secrets.BUCKET_NAME }}
        run: terraform apply -auto-approve
        working-directory: terraform

      - name: Uploading files to S3 Bucket
        run: |
          aws s3 sync frontend/dist/ s3://${{ secrets.BUCKET_NAME }}/ --delete
